import type { Experience } from "@/content/experience";
import type { Project } from "@/content/projects";

export type Locale = "pt" | "en" | "es";

export const ui = {
  pt: {
    language: "Idioma", theme: "Alternar tema", projectsNav: "Projetos", experienceNav: "Experiência", aboutNav: "Sobre", contactNav: "Contato", navigation: "Navegação principal",
    name: "Murilo Patrício", location: "Full stack developer / São Paulo", heroBefore: "Software para", heroAccent: "processos", heroAfter: "que precisam funcionar.", intro: "Construo produtos web, APIs e automações que conectam dados, pessoas e operações com clareza e confiabilidade.", current: "Atualmente, atuo como Desenvolvedor Full Stack na Hendrios ACE, criando sistemas, automações e integrações que tornam processos operacionais mais eficientes e confiáveis.", flowInput: "entrada", flowProcesses: "processos", flowIntegrations: "integrações", flowOutput: "saída",
    selectedProjects: "Projetos selecionados", projectsIntro: "Projetos autorais que mostram minha prática em produtos digitais, back-end e arquitetura de sistemas.", viewProjects: "Ver projetos", viewCase: "Ver estudo de caso", explore: "Explorar",
    professionalExperience: "Experiência profissional", experienceIntro: "Experiência profissional e projetos próprios são apresentados separadamente: aqui estão responsabilidades e contexto de trabalho, sem expor sistemas internos.",
    about: "Sobre", aboutTitle: "Boa tecnologia resolve o que importa — sem fazer barulho.", aboutText: "Sou desenvolvedor full stack e estudante de Engenharia de Software. Gosto de entender o problema antes da interface e de construir soluções sustentadas por uma base técnica sólida.", aboutFocus: "Minha experiência reúne produtos web, automação de processos e integrações. Atualmente aprofundo fundamentos de sistemas distribuídos, qualidade e IA aplicada.", seeCode: "Conhecer meu código",
    stack: "Stack", stackIntro: "Tecnologias organizadas pelo papel que exercem no produto.", frontend: "Frontend", backend: "Backend", dataInfrastructure: "Dados e infraestrutura", automation: "Automação", education: "Formação", personalProjects: "Prática independente", contact: "Contato", contactBefore: "Vamos construir algo que", contactAccent: "funcione", contactAfter: "bem?", contactText: "Acompanhe meus projetos e entre em contato pelo GitHub.",
    allProjects: "Todos os projetos", viewCode: "Ver código", context: "Contexto", problem: "Problema", approach: "Abordagem", decisions: "Decisões técnicas", stackScope: "Stack e escopo", rights: "Todos os direitos reservados.",
  },
  en: {
    language: "Language", theme: "Toggle theme", projectsNav: "Projects", experienceNav: "Experience", aboutNav: "About", contactNav: "Contact", navigation: "Primary navigation",
    name: "Murilo Patrício", location: "Full-stack developer / São Paulo", heroBefore: "Software for", heroAccent: "processes", heroAfter: "that need to work.", intro: "I build web products, APIs, and automations that connect data, people, and operations with clarity and reliability.", current: "I currently work as a Full-Stack Developer at Hendrios ACE, building systems, automations, and integrations that make operational processes more efficient and reliable.", flowInput: "input", flowProcesses: "processes", flowIntegrations: "integrations", flowOutput: "output",
    selectedProjects: "Selected projects", projectsIntro: "Independent projects that showcase my work with digital products, back-end development, and systems architecture.", viewProjects: "View projects", viewCase: "View case study", explore: "Explore",
    professionalExperience: "Professional experience", experienceIntro: "Professional experience and independent projects are presented separately: these are my responsibilities and work context, without exposing internal systems.",
    about: "About", aboutTitle: "Good technology solves what matters — quietly.", aboutText: "I’m a full-stack developer and Software Engineering student. I like understanding the problem before the interface and building solutions on a solid technical foundation.", aboutFocus: "My experience spans web products, process automation, and integrations. I’m currently deepening my knowledge of distributed systems, quality, and applied AI.", seeCode: "See my code",
    stack: "Stack", stackIntro: "Technologies organized by the role they play in a product.", frontend: "Frontend", backend: "Backend", dataInfrastructure: "Data and infrastructure", automation: "Automation", education: "Education", personalProjects: "Independent practice", contact: "Contact", contactBefore: "Let’s build something that", contactAccent: "works", contactAfter: "well.", contactText: "Follow my projects and get in touch through GitHub.",
    allProjects: "All projects", viewCode: "View code", context: "Context", problem: "Problem", approach: "Approach", decisions: "Technical decisions", stackScope: "Stack and scope", rights: "All rights reserved.",
  },
  es: {
    language: "Idioma", theme: "Cambiar tema", projectsNav: "Proyectos", experienceNav: "Experiencia", aboutNav: "Sobre mí", contactNav: "Contacto", navigation: "Navegación principal",
    name: "Murilo Patrício", location: "Desarrollador full stack / São Paulo", heroBefore: "Software para", heroAccent: "procesos", heroAfter: "que necesitan funcionar.", intro: "Construyo productos web, APIs y automatizaciones que conectan datos, personas y operaciones con claridad y fiabilidad.", current: "Actualmente trabajo como Desarrollador Full Stack en Hendrios ACE, creando sistemas, automatizaciones e integraciones que hacen los procesos operativos más eficientes y fiables.", flowInput: "entrada", flowProcesses: "procesos", flowIntegrations: "integraciones", flowOutput: "salida",
    selectedProjects: "Proyectos seleccionados", projectsIntro: "Proyectos independientes que muestran mi práctica en productos digitales, back-end y arquitectura de sistemas.", viewProjects: "Ver proyectos", viewCase: "Ver caso de estudio", explore: "Explorar",
    professionalExperience: "Experiencia profesional", experienceIntro: "La experiencia profesional y los proyectos propios se presentan por separado: estas son mis responsabilidades y el contexto de trabajo, sin exponer sistemas internos.",
    about: "Sobre mí", aboutTitle: "La buena tecnología resuelve lo que importa — sin hacer ruido.", aboutText: "Soy desarrollador full stack y estudiante de Ingeniería de Software. Me gusta entender el problema antes de la interfaz y construir soluciones con una base técnica sólida.", aboutFocus: "Mi experiencia reúne productos web, automatización de procesos e integraciones. Actualmente profundizo en sistemas distribuidos, calidad e IA aplicada.", seeCode: "Ver mi código",
    stack: "Tecnologías", stackIntro: "Tecnologías organizadas según el papel que cumplen en el producto.", frontend: "Frontend", backend: "Backend", dataInfrastructure: "Datos e infraestructura", automation: "Automatización", education: "Formación", personalProjects: "Práctica independiente", contact: "Contacto", contactBefore: "Construyamos algo que", contactAccent: "funcione", contactAfter: "bien.", contactText: "Sigue mis proyectos y ponte en contacto a través de GitHub.",
    allProjects: "Todos los proyectos", viewCode: "Ver código", context: "Contexto", problem: "Problema", approach: "Enfoque", decisions: "Decisiones técnicas", stackScope: "Tecnologías y alcance", rights: "Todos los derechos reservados.",
  },
} as const;

type ProjectCopy = Pick<Project, "eyebrow" | "description" | "overview" | "problem" | "solution" | "decisions" | "imageAlt" | "metrics">;

const projectTranslations: Record<"en" | "es", Record<string, ProjectCopy>> = {
  en: {
    subapp: { eyebrow: "SaaS · payments", description: "A study of an application for organizing subscriptions and exploring a recurring payment flow.", overview: "Subapp explores a subscription management experience: registration, authentication, plans, and a protected area based on subscription status.", problem: "Recurring billing requires a clear flow between registration, payment, and access control — areas that need to maintain consistent state.", solution: "The project combines a Next.js interface with Supabase for authentication and data, plus Stripe Checkout and webhooks to explore the payment lifecycle.", decisions: ["Next.js brings the interface and API routes together in one project.", "Supabase provides authentication and a PostgreSQL database for the study.", "Stripe Checkout and webhook signature verification structure the payment flow."], imageAlt: "Visual representation of Subapp’s subscription flow", metrics: [{ label: "Type", value: "SaaS study" }, { label: "Focus", value: "Payments" }] },
    shoeapi: { eyebrow: "E-commerce · full stack", description: "An e-commerce study that separates a Java REST API from an Angular interface.", overview: "The project brings together the ShoeAPI back end and ShoeInterface front end to practice separating responsibilities between a web client and a data service.", problem: "An e-commerce experience requires the interface and API to evolve with clearly defined responsibilities.", solution: "The approach combines a Spring Boot API, an Angular front end, and document-oriented modeling for the footwear domain.", decisions: ["Spring Boot structures the API layer and application services.", "Angular keeps the interface independent from the back end.", "MongoDB was used to explore flexible catalog modeling."], imageAlt: "Visual representation of the ShoeAPI and ShoeInterface architecture", metrics: [{ label: "Type", value: "Full-stack study" }, { label: "Domain", value: "E-commerce" }] },
    microservices: { eyebrow: "Architecture · proof of concept", description: "A study environment for exploring common distributed-system dependencies in containers.", overview: "A proof of concept that organizes a local environment with data, cache, and messaging services to support the study of modular architecture.", problem: "Before splitting real services, it is important to understand how a relational database, cache, and messaging coexist in a reproducible environment.", solution: "The repository configures PostgreSQL, Redis, and RabbitMQ with Docker Compose and starts a Spring Boot application as a foundation for further experiments.", decisions: ["Docker Compose makes the local infrastructure reproducible.", "RabbitMQ was included to study asynchronous communication.", "Redis and PostgreSQL make it possible to explore caching and relational persistence in the same environment."], imageAlt: "Visual representation of the project’s infrastructure services", metrics: [{ label: "Type", value: "Proof of concept" }, { label: "Focus", value: "Local infrastructure" }] },
  },
  es: {
    subapp: { eyebrow: "SaaS · pagos", description: "Estudio de una aplicación para organizar suscripciones y explorar un flujo de pagos recurrentes.", overview: "Subapp explora una experiencia de gestión de suscripciones: registro, autenticación, planes y un área protegida basada en el estado de la suscripción.", problem: "Los cobros recurrentes requieren un flujo claro entre registro, pago y control de acceso, áreas que deben mantener un estado consistente.", solution: "El proyecto combina una interfaz en Next.js con Supabase para autenticación y datos, además de Stripe Checkout y webhooks para explorar el ciclo de pago.", decisions: ["Next.js reúne la interfaz y las rutas de API en un mismo proyecto.", "Supabase proporciona autenticación y una base PostgreSQL para el estudio.", "Stripe Checkout y la verificación de firma del webhook estructuran el flujo de pago."], imageAlt: "Representación visual del flujo de suscripciones de Subapp", metrics: [{ label: "Tipo", value: "Estudio SaaS" }, { label: "Enfoque", value: "Pagos" }] },
    shoeapi: { eyebrow: "Comercio electrónico · full stack", description: "Estudio de comercio electrónico que separa una API REST en Java de una interfaz Angular.", overview: "El proyecto reúne el back end ShoeAPI y la interfaz ShoeInterface para practicar la división de responsabilidades entre el cliente web y el servicio de datos.", problem: "Una experiencia de comercio electrónico exige que la interfaz y la API puedan evolucionar con responsabilidades bien definidas.", solution: "La propuesta combina una API en Spring Boot con un front end Angular y un modelado orientado a documentos para el dominio del calzado.", decisions: ["Spring Boot estructura la capa de API y los servicios de la aplicación.", "Angular mantiene la interfaz independiente del back end.", "MongoDB se utilizó para explorar un modelado flexible del catálogo."], imageAlt: "Representación visual de la arquitectura de ShoeAPI y ShoeInterface", metrics: [{ label: "Tipo", value: "Estudio full stack" }, { label: "Dominio", value: "Comercio electrónico" }] },
    microservices: { eyebrow: "Arquitectura · prueba de concepto", description: "Entorno de estudio para explorar dependencias comunes de sistemas distribuidos en contenedores.", overview: "Una prueba de concepto que organiza un entorno local con servicios de datos, caché y mensajería para apoyar el estudio de una arquitectura modular.", problem: "Antes de separar servicios reales, es importante comprender cómo conviven una base de datos relacional, la caché y la mensajería en un entorno reproducible.", solution: "El repositorio configura PostgreSQL, Redis y RabbitMQ con Docker Compose e inicia una aplicación Spring Boot como base para futuros experimentos.", decisions: ["Docker Compose hace reproducible la infraestructura local.", "RabbitMQ se incluyó para estudiar la comunicación asíncrona.", "Redis y PostgreSQL permiten explorar la caché y la persistencia relacional en el mismo entorno."], imageAlt: "Representación visual de los servicios de infraestructura del proyecto", metrics: [{ label: "Tipo", value: "Prueba de concepto" }, { label: "Enfoque", value: "Infraestructura local" }] },
  },
};

export function localizeProject(project: Project, locale: Locale): Project {
  if (locale === "pt") return project;
  return { ...project, ...projectTranslations[locale][project.slug] };
}

const experienceTranslations: Record<"en" | "es", Record<string, Omit<Experience, "company">>> = {
  en: {
    "Hendrios ACE": { role: "Full-Stack Developer", period: "May 2026 — present", description: "I develop and evolve digital solutions, connecting web applications, automations, and integrations to support business operations.", highlights: ["Development of front-end and back-end features with a focus on quality and maintainability.", "Process automation and integration between systems and services.", "Support for continuous improvement of internal workflows and solution reliability."] },
    KTGROUP: { role: "Full-Stack Developer · Support Team Intern", period: "Jun 2024 — May 2025 · hybrid", description: "I worked on internal and external applications, contributing technical specifications, improvements, and new features across different parts of the product.", highlights: ["Worked with Java, Node.js, JavaScript, MongoDB, and C#.", "Supported performance, scalability, and routine-automation improvements.", "Contributed to reported reductions in system response times and gains in team productivity."] },
    "Gold Cred": { role: "Front-End Developer · Freelance", period: "Aug 2023 — Dec 2023 · remote", description: "Developed a website for a credit brokerage in collaboration with other developers, focusing on digital presence and customer communication.", highlights: ["Implemented web interfaces using development best practices.", "Contributed to clearer digital communication and business-reported commercial results."] },
    "Projetos independentes": { role: "Full-stack developer", period: "2023 — present", description: "I build end-to-end products to deepen my experience with interfaces, APIs, payments, data, and systems architecture." },
    Formação: { role: "Software Engineering · Descomplica", period: "2025 — in progress", description: "Completed a Systems Analysis and Development degree at SENAC in 2025. I am currently deepening my knowledge of software engineering and distributed systems." },
  },
  es: {
    "Hendrios ACE": { role: "Desarrollador Full Stack", period: "may 2026 — actualidad", description: "Desarrollo y evoluciono soluciones digitales, conectando aplicaciones web, automatizaciones e integraciones para apoyar las operaciones del negocio.", highlights: ["Desarrollo de funcionalidades front-end y back-end con foco en calidad y mantenimiento.", "Automatización de procesos e integración entre sistemas y servicios.", "Apoyo a la mejora continua de los flujos internos y a la fiabilidad de las soluciones."] },
    KTGROUP: { role: "Desarrollador Full Stack · Becario del equipo de soporte", period: "jun 2024 — may 2025 · híbrido", description: "Trabajé en aplicaciones internas y externas, aportando especificaciones técnicas, mejoras y nuevas funcionalidades en distintas partes del producto.", highlights: ["Trabajo con Java, Node.js, JavaScript, MongoDB y C#.", "Apoyo a mejoras de rendimiento, escalabilidad y automatización de rutinas.", "Contribución a reducciones reportadas en el tiempo de respuesta de los sistemas y a mejoras de productividad del equipo."] },
    "Gold Cred": { role: "Desarrollador Front-End · Freelance", period: "ago 2023 — dic 2023 · remoto", description: "Desarrollo de un sitio web para una promotora de crédito, en colaboración con otros desarrolladores y con foco en presencia digital y comunicación con clientes.", highlights: ["Implementación de interfaces web y buenas prácticas de desarrollo.", "Contribución a una comunicación digital más clara y a resultados comerciales reportados por el negocio."] },
    "Projetos independentes": { role: "Desarrollador full stack", period: "2023 — actualidad", description: "Desarrollo productos de principio a fin para profundizar mi experiencia en interfaces, APIs, pagos, datos y arquitectura de sistemas." },
    Formação: { role: "Ingeniería de Software · Descomplica", period: "2025 — en curso", description: "Finalicé Análisis y Desarrollo de Sistemas en SENAC en 2025. Actualmente profundizo en ingeniería de software y sistemas distribuidos." },
  },
};

export function localizeExperience(item: Experience, locale: Locale): Experience {
  if (locale === "pt") return item;
  const translated = experienceTranslations[locale][item.company];
  const company = item.company === "Projetos independentes" ? (locale === "en" ? "Independent projects" : "Proyectos independientes") : item.company === "Formação" ? (locale === "en" ? "Education" : "Formación") : item.company;
  return { company, ...translated };
}
